meta_product_name: "CrewCall"
meta_title: "CrewCall - Media Crew Onboarding Platform"
meta_description: "CrewCall is a Progressive Web App (PWA) written with the Ruby on Rails framework. It is an onboarding platform to connect Producers with Film/Media freelance crew."
meta_image: "CrewcallLogo2.png" # should exist in `app/assets/images/`
